language: csharp
solution: SekiDiscord.sln
dotnet: 2.1.502
install:
  - nuget restore SekiDiscord.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - dotnet restore
  - msbuild /p:Configuration=Release SekiDiscord.sln
  - dotnet test